site_name: Learning XIDs from the Command Line
site_url: https://learningxids.blockchaincommons.com
repo_url: https://github.com/BlockchainCommons/XID-Quickstart

theme:
  name: material
  color_mode: dark
  user_color_mode_toggle: true
  icon:
    logo: material/close-box
